### ISSUE TITLE
This is awesome

### ISSUE THREAD

**Issue by chmac** [cryptoboid/splitio#1]
Thank you. This is awesome. p2p database, client side encryption, no need for accounts. This is precisely what I had in mind when I thought about trying to find an open source tool. Thank you for publishing it.

I'd suggest adding the `split-expenses` and `bill-splitting` topics to this GitHub repo as I think that could help other people find it.

As an aside, if I can do anything to help support this project, like run a db replica node or something (don't know much about gundb off the top of my head), just let me know, would be happy to help and will try to promote this hard every time somebody suggests another splitwise group.

**Comment by cryptoboid** [comment]
Thank you! Glad you find it useful. Right now I'm using community servers as relays, but we may need a self-hosted one down the line. I'll add the topics just in case
