### ISSUE TITLE
Add confirm dialog on delete?

### ISSUE THREAD

**Issue by chmac** [cryptoboid/splitio#2]
I think it would make sense to add a "are you sure" check, even with a simple `globalThis.prompt()` on deleting expenses. It's a bit too easy to double click for example and delete an expense which I guess there's no way to recover. At least I don't see any obvious undo / redo type functionality.

**Comment by cryptoboid** [comment]
Agreed! It is something I've considered for sure, will add it soon!

**Comment by chmac** [comment]
I'm happy to submit a PR if you like, using a confirm it should be easy.

**Comment by cryptoboid** [comment]
Added with last commit. Wanted to give it a materialUI dialog for consistency :)

![image](https://user-images.githubusercontent.com/77416692/155638745-ca72960e-dcd1-40c4-bb15-12c577cdf251.png)

**Comment by chmac** [comment]
Awesome! Big improvement for the feeling of safety using the app, thanks for the quick turnaround.
