### ISSUE TITLE
List "recent" groups?

### ISSUE THREAD

**Issue by chmac** [cryptoboid/splitio#3]
It would be awesome if I could see a list of my recently visited groups (for example saved in localStorage) on the homepage. That would make it much more user friendly to jump between groups.

**Comment by cryptoboid** [comment]
This came up when I was testing the PWA functionality, because you can't create a shortcut to a specific page. I haven't considered it since, because I've just used those browser shortcuts. I was thinking more of a 'favorites' list, instead of recent groups, but I'm open to suggestions :)

**Comment by chmac** [comment]
Here's an example of a user journey:

- Find the tool, load the page
- Create a group
- Add some people and expenses
- Close tab
- Following day, open site again
- Stare at a blank page that says "enter your group id"
- Wonder what a group ID even is never mind what yours might be... 🤔 

I had paid attention to the "enter your group ID" part, so by the time I was on a group page, I figured that I'd better save the URL.

I think there's a few things that would make this clearer:

- Tell users to save their group ID after they create the group
  - Also tell them what it is (as in, put it in an `<input` to make it easily copied)
- Automatically keep a log of the last n groups they have visited in localStorage and show that on the homepage

Favourites would be a cool feature, but I'd suggest making it "opt out" instead of "opt in". As in, showing a list of all recently viewed groups, with the option to remove from that list, rather than giving people the option to explicitly add a group to a list.

Put differently, for the average user, there's a very real chance they will put data into this tool and never be able to find it again. The advantage of not having to register has it's downsides in that there's no "forgot your password, just give us your email" option! :-)

**Comment by cryptoboid** [comment]
Implemented in #10 ! I'll maybe add deleting/opting-out later. Currently remembers up to 5 recent groups. Thanks for the suggestion!
