### ISSUE TITLE
Person only shows 4 people

### ISSUE THREAD

**Issue by chmac** [cryptoboid/splitio#5]
Screenshot to show the issue:

<img width="389" alt="Screenshot 2022-02-23 at 22 21 54" src="https://user-images.githubusercontent.com/690997/155410652-454bb025-865d-43c9-8026-73a5acfba758.png">

There are 6 people in our group, but the dropdown somehow goes upwards from the cursor and gets hidden in the top of the modal or something. I can use the arrow keys to select down the list, but it's a bit weird. This is on a huge laptop screen.

**Comment by cryptoboid** [comment]
Yeah, I've noticed it a while ago but didn't have the time to go through the CSS. I've just pushed a fix for it, let me know if it works!

Also, I've added the ability to record payments/settlements a few days ago, also looking for feedback :)

**Comment by chmac** [comment]
Awesome, works great!
